// src/mockData.js
export const MOCK_USERS = [
    {
        id: 'user1',
        username: 'ChefAditya',
        email: 'aditya@example.com',
        profilePicture: 'https://via.placeholder.com/150/FFA500/FFFFFF?Text=UserA',
        dietaryRestrictions: ['Vegetarian'],
        favoriteCuisines: ['Italian', 'Indian'],
        savedRecipeIds: ['recipe2'],
        createdRecipeIds: ['recipe1', 'recipe3'],
    },
    {
        id: 'user2',
        username: 'FoodieJane',
        email: 'jane@example.com',
        profilePicture: 'https://via.placeholder.com/150/008000/FFFFFF?Text=UserJ',
        dietaryRestrictions: [],
        favoriteCuisines: ['Mexican'],
        savedRecipeIds: ['recipe1'],
        createdRecipeIds: ['recipe2'],
    },
];

export const MOCK_RECIPES = [
    {
        id: 'recipe1',
        title: 'Classic Tomato Pasta',
        ingredients: [
            { name: 'Pasta', quantity: '200g' },
            { name: 'Tomato Sauce', quantity: '1 can' },
            { name: 'Garlic', quantity: '2 cloves' },
            { name: 'Olive Oil', quantity: '2 tbsp' },
            { name: 'Basil', quantity: 'a few leaves' },
        ],
        instructions: '1. Cook pasta. 2. Sauté garlic in olive oil. 3. Add tomato sauce. 4. Mix with pasta and basil.',
        photos: ['https://via.placeholder.com/600x400/FF0000/FFFFFF?Text=Pasta'],
        authorId: 'user1',
        authorUsername: 'ChefAditya',
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), // 2 days ago
        likes: ['user2'],
        comments: [
            { id: 'c1', userId: 'user2', username: 'FoodieJane', text: 'Looks delicious!', timestamp: new Date().toISOString() },
        ],
        saves: 1,
        cuisineType: 'Italian',
        difficultyLevel: 'Easy',
        dietaryRestrictions: ['Vegetarian'],
    },
    {
        id: 'recipe2',
        title: 'Spicy Chicken Tacos',
        ingredients: [
            { name: 'Chicken Breast', quantity: '1 lb' },
            { name: 'Taco Shells', quantity: '8' },
            { name: 'Salsa', quantity: '1 cup' },
            { name: 'Chili Powder', quantity: '1 tsp' },
        ],
        instructions: '1. Cook chicken with chili powder. 2. Shred chicken. 3. Fill taco shells with chicken and salsa.',
        photos: ['https://via.placeholder.com/600x400/00FF00/000000?Text=Tacos'],
        authorId: 'user2',
        authorUsername: 'FoodieJane',
        timestamp: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
        likes: ['user1'],
        comments: [],
        saves: 1,
        cuisineType: 'Mexican',
        difficultyLevel: 'Medium',
        dietaryRestrictions: [],
    },
    {
        id: 'recipe3',
        title: 'Simple Veggie Stir-fry',
        ingredients: [
            { name: 'Mixed Vegetables', quantity: '500g' },
            { name: 'Soy Sauce', quantity: '3 tbsp' },
            { name: 'Tofu (optional)', quantity: '200g' },
            { name: 'Rice', quantity: 'for serving' },
        ],
        instructions: '1. Chop vegetables. 2. Stir-fry vegetables (and tofu if using). 3. Add soy sauce. 4. Serve with rice.',
        photos: ['https://via.placeholder.com/600x400/0000FF/FFFFFF?Text=StirFry'],
        authorId: 'user1',
        authorUsername: 'ChefAditya',
        timestamp: new Date().toISOString(),
        likes: [],
        comments: [],
        saves: 0,
        cuisineType: 'Asian',
        difficultyLevel: 'Easy',
        dietaryRestrictions: ['Vegetarian', 'Vegan'],
    },
];